services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

    volumes:
      - rabbit-mq/config:/var/lib/rabbitmq/
       - rabbit-mq/log:/var/log/rabbitmq

volumes:
  rabbit-mq:
